import type { GitDeltaTarget, Theme } from '../theme-schema.ts';
import { batThemeName } from './bat-renderer.ts';

const OTHEME_INCLUDE_PATH = '~/.config/git/otheme-delta.conf';
const INCLUDE_PATH_LINE = `\tpath = ${OTHEME_INCLUDE_PATH}`;

/** Returns the absolute path (relative to HOME) of the otheme delta include file. */
export const gitDeltaConfRelPath = '.config/git/otheme-delta.conf';

/** Returns the managed include path used inside .gitconfig [include] blocks. */
export const gitDeltaIncludePath = OTHEME_INCLUDE_PATH;

/** Renders the [delta] config section derived from the theme palette. */
export const renderGitDeltaConf = (
  theme: Theme,
  target: GitDeltaTarget,
): string => {
  const lines = [
    '# Generated by otheme — do not edit manually',
    '[delta]',
    `\tfeatures = ${target.features}`,
    // After features so it overrides any syntax-theme the preset sets. delta
    // delegates syntax highlighting to bat; this points at the otheme-derived
    // bat theme so diff token colors match the active theme. Requires the bat
    // target to be enabled so the referenced theme exists.
    `\tsyntax-theme = ${batThemeName(theme)}`,
    `\tminus-style = syntax "${theme.ui.diffDel}"`,
    `\tminus-emph-style = syntax "${theme.ui.error}"`,
    `\tplus-style = syntax "${theme.ui.diffAdd}"`,
    `\tplus-emph-style = syntax "${theme.ui.success}"`,
    `\tzero-style = syntax "${theme.ui.bg}"`,
    `\tline-numbers-zero-style = "${theme.ui.lineNr}"`,
    `\tline-numbers-minus-style = "${theme.ui.error}"`,
    `\tline-numbers-plus-style = "${theme.ui.success}"`,
  ];

  return `${lines.join('\n')}\n`;
};

/** True when the gitconfig content already includes the otheme delta conf. */
export const hasOthemeInclude = (gitconfigContent: string): boolean =>
  gitconfigContent.includes(INCLUDE_PATH_LINE);

/** Prepends the [include] block for otheme-delta.conf to the gitconfig content. */
export const addOthemeInclude = (gitconfigContent: string): string => {
  const block = `[include]\n${INCLUDE_PATH_LINE}\n`;

  if (gitconfigContent.length === 0) {
    return `${block}\n`;
  }

  return `${block}\n${gitconfigContent}`;
};
