export const hunkThemeTokens = [
  'background',
  'panel',
  'panelAlt',
  'border',
  'accent',
  'accentMuted',
  'text',
  'muted',
  'addedBg',
  'removedBg',
  'movedAddedBg',
  'movedRemovedBg',
  'contextBg',
  'addedContentBg',
  'removedContentBg',
  'contextContentBg',
  'addedSignColor',
  'removedSignColor',
  'lineNumberBg',
  'lineNumberFg',
  'selectedHunk',
  'badgeAdded',
  'badgeRemoved',
  'badgeNeutral',
  'fileNew',
  'fileDeleted',
  'fileRenamed',
  'fileModified',
  'fileUntracked',
  'noteBorder',
  'noteBackground',
  'noteTitleBackground',
  'noteTitleText',
  'syntaxDefault',
  'syntaxKeyword',
  'syntaxString',
  'syntaxComment',
  'syntaxNumber',
  'syntaxFunction',
  'syntaxProperty',
  'syntaxType',
  'syntaxVariable',
  'syntaxOperator',
  'syntaxPunctuation',
] as const;

export type HunkThemeToken = (typeof hunkThemeTokens)[number];
